# SF Salaries Exercise - Solutions

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [5]:
!pip install kagglehub
import pandas as pd
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kaggle/sf-salaries")

print("Path to dataset files:", path)

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\snehal.naik\appdata\roaming\python\python314\site-packages (from kagglehub) (26.0)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting requests (from kagglehub)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting charset_normalizer<4,>=2 (from requests->kagglehub)
  Downloading charset_normalizer-3.4.5-cp314-cp314-win_amd64.whl.metadata (39 kB)
Collecting idna<4,>=2.5 (from requests->kagglehub)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->kagglehub)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests->kagglehub)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: colorama in c:\users\snehal.naik\appdata\roaming\python\python314\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl (437 kB)
Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.5-cp314-cp314-win_amd64.whl (143 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: urllib3, tqdm, pyyaml, protobuf, idna, charset_normalizer, certifi, requests, kagglesdk, kagglehub

   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ----------------------------------------  0/10 [urllib3]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   ---- -----------------------------------  1/10 [tqdm]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   -------- -------------------------------  2/10 [pyyaml]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ------------ ---------------------------  3/10 [protobuf]
   ---------------- -----------------------  4/10 [idna]
   ---------------- -----------------------  4/10 [idna]
   ---------------- -----------------------  4/10 [idna]
   ---------------- -----------------------  4/10 [idna]
   ---------------- -----------------------  4/10 [idna]
   ---------------- -----------------------  4/10 [idna]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   -------------------- -------------------  5/10 [charset_normalizer]
   ------------------------ ---------------  6/10 [certifi]
   ------------------------ ---------------  6/10 [certifi]
   ------------------------ ---------------  6/10 [certifi]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   ---------------------------- -----------  7/10 [requests]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   -------------------------------- -------  8/10 [kagglesdk]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ------------------------------------ ---  9/10 [kagglehub]
   ---------------------------------------- 10/10 [kagglehub]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.5 idna-3.11 kagglehub-1.0.0 kagglesdk-0.1.16 protobuf-7.34.0 pyyaml-6.0.3 requests-2.32.5 tqdm-4.67.3 urllib3-2.6.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
c:\Users\Snehal.Naik\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Snehal.Naik\.cache\kagglehub\datasets\kaggle\sf-salaries\5.archive...

100%|██████████| 11.5M/11.5M [00:02<00:00, 5.25MB/s]

Extracting files...

Path to dataset files: C:\Users\Snehal.Naik\.cache\kagglehub\datasets\kaggle\sf-salaries\versions\5

** Read Salaries.csv as a dataframe called sal.**

In [8]:
sal = pd.read_csv('D:\Python\opus_files-main\Salaries.csv')

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\Snehal.Naik\AppData\Local\Temp\ipykernel_24080\1573251346.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  sal = pd.read_csv('D:\Python\opus_files-main\Salaries.csv')
C:\Users\Snehal.Naik\AppData\Local\Temp\ipykernel_24080\1573251346.py:1: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('D:\Python\opus_files-main\Salaries.csv')

** Check the head of the DataFrame. **

In [9]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [10]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(3), int64(2), object(4), str(4)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [14]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors = 'coerce')
sal['BasePay'].mean()

np.float64(66325.44884048769)

** What is the highest amount of OvertimePay in the dataset ? **

In [16]:
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors = 'coerce')
sal['OvertimePay'].max()

np.float64(245131.88)

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [17]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'].iloc[0]

'CAPTAIN, FIRE SUPPRESSION'

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [19]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits'].iloc[0]

np.float64(270324.91)

** What is the name of highest paid person (including benefits)?**

In [21]:
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [22]:
sal.loc[sal['TotalPayBenefits'].idxmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                    0.0
OvertimePay                                0.0
OtherPay                               -618.13
Benefits                                  0.00
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                      PT
Name: 148653, dtype: object

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [23]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'] , errors = 'coerce')
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [24]:
sal['JobTitle'].nunique()

2159

** What are the top 5 most common jobs? **

In [25]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [26]:
sal[sal['Year'] == 2013].groupby('JobTitle').size().eq(1).sum()

np.int64(202)

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [30]:
sal['JobTitle'].str.contains('Chief',case = False).sum()

np.int64(627)

477

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [31]:
sal['TotalPayBenefits'] = pd.to_numeric(sal['TotalPayBenefits'] , errors = 'coerce')
sal['title_len'] = sal['JobTitle'].apply(len)
sal['title_len'].corr(sal['TotalPayBenefits'])

np.float64(-0.03687844593260669)

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!